// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByFkj70rYD5C4QZk0cB_F7dQVdGwDg_fg',
    appId: '1:762409043159:web:15d22eb039754d698e5c92',
    messagingSenderId: '762409043159',
    projectId: 'gappsdd-49b50',
    authDomain: 'gappsdd-49b50.firebaseapp.com',
    storageBucket: 'gappsdd-49b50.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcVDgyY5jf7BHLC2k814xQ79wENR7iY3c',
    appId: '1:762409043159:android:bb6da72f7d9dc58a8e5c92',
    messagingSenderId: '762409043159',
    projectId: 'gappsdd-49b50',
    storageBucket: 'gappsdd-49b50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrNEONUs9fXqp0ChcSdh9AcLQH420w5Pw',
    appId: '1:762409043159:ios:11286e918381e3e58e5c92',
    messagingSenderId: '762409043159',
    projectId: 'gappsdd-49b50',
    storageBucket: 'gappsdd-49b50.firebasestorage.app',
    iosBundleId: 'com.example.gappsdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrNEONUs9fXqp0ChcSdh9AcLQH420w5Pw',
    appId: '1:762409043159:ios:11286e918381e3e58e5c92',
    messagingSenderId: '762409043159',
    projectId: 'gappsdd-49b50',
    storageBucket: 'gappsdd-49b50.firebasestorage.app',
    iosBundleId: 'com.example.gappsdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByFkj70rYD5C4QZk0cB_F7dQVdGwDg_fg',
    appId: '1:762409043159:web:631ff86a76c8b99c8e5c92',
    messagingSenderId: '762409043159',
    projectId: 'gappsdd-49b50',
    authDomain: 'gappsdd-49b50.firebaseapp.com',
    storageBucket: 'gappsdd-49b50.firebasestorage.app',
  );
}
